// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/PereRohit/test-service/internal/logic (interfaces: TestServiceLogicIer)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/PereRohit/test-service/internal/model"
	model0 "github.com/PereRohit/util/model"
	gomock "github.com/golang/mock/gomock"
)

// MockTestServiceLogicIer is a mock of TestServiceLogicIer interface.
type MockTestServiceLogicIer struct {
	ctrl     *gomock.Controller
	recorder *MockTestServiceLogicIerMockRecorder
}

// MockTestServiceLogicIerMockRecorder is the mock recorder for MockTestServiceLogicIer.
type MockTestServiceLogicIerMockRecorder struct {
	mock *MockTestServiceLogicIer
}

// NewMockTestServiceLogicIer creates a new mock instance.
func NewMockTestServiceLogicIer(ctrl *gomock.Controller) *MockTestServiceLogicIer {
	mock := &MockTestServiceLogicIer{ctrl: ctrl}
	mock.recorder = &MockTestServiceLogicIerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestServiceLogicIer) EXPECT() *MockTestServiceLogicIerMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockTestServiceLogicIer) HealthCheck() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockTestServiceLogicIerMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockTestServiceLogicIer)(nil).HealthCheck))
}

// Ping mocks base method.
func (m *MockTestServiceLogicIer) Ping(arg0 *model.PingRequest) *model0.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(*model0.Response)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockTestServiceLogicIerMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockTestServiceLogicIer)(nil).Ping), arg0)
}
